micronaut:
  application:
    name: gateway

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'changeThisWithYourSecressssasdsadsadsadsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssaddsadsadsadsadsadsadsadsadsadsadsadsat'
              refresh-token-expiration: 3600
              access-token-expiration: 3600
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
---
jpa:
  default:
    packages-to-scan:
      - 'gateway.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true